version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "exilesprx"

  - package-ecosystem: "docker"
    directory: ".docker"
    schedule:
      interval: "weekly"
    reviewers:
      - "exilesprx"
